---
- name: Restart ntopng
  systemd:
      name: ntopng
      enabled: yes
      state: restarted

- name: Restart httpd
  systemd:
      name: httpd
      enabled: yes
      state: restarted

- name: Restart postfix
  systemd:
      name: postfix
      enabled: yes
      state: restarted

- name: Restart bolo
  systemd:
      name: bolo
      enabled: yes
      state: restarted

- name: Restart free
  systemd:
      name: free
      enabled: yes
      state: restarted

- name: Restart rsyslog
  systemd:
      name: rsyslog
      enabled: yes
      state: restarted
