---
- name: Restart ntopng
  become: yes
  systemd:
      name: ntopng
      enabled: yes
      state: restarted

- name: Restart httpd
  become: yes
  systemd:
      name: httpd
      enabled: yes
      state: restarted

- name: Restart postfix
  become: yes
  systemd:
      name: postfix
      enabled: yes
      state: restarted

- name: Restart bolo
  become: yes
  systemd:
      name: bolo
      enabled: yes
      state: restarted

- name: Restart free
  become: yes
  systemd:
      name: free
      enabled: yes
      state: restarted

- name: Restart rsyslog
  become: yes
  systemd:
      name: rsyslog
      enabled: yes
      state: restarted
